In [1]:
import pandas as pd
import os

In [4]:
path = '/home/shiva/Datasets/V2_01_easy/V2_01_easy/Custom_Datasets/'

In [54]:
for dir_name in next(os.walk(path))[1][1:]:
    print(dir_name)
    df = pd.read_csv(f'{path}/{dir_name}/mav0/imu0/data.csv')
    cols = df.columns.tolist()
    temp = cols[1:4]
    del(cols[1])
    del(cols[1])
    del(cols[1])
    cols.insert(1, temp[0])
    cols.insert(1, temp[1])
    cols.insert(1, temp[2])
    df = df[cols]
    df.to_csv(f'{path}/{dir_name}/mav0/imu0/data.csv', index=False)
    # to_remove = []
    # for col in df.columns.tolist():
    #     if 'Unnamed:' in col:
    #         to_remove.append(col)
    # df.drop(columns = to_remove, inplace=True)
    # df.to_csv(f'{path}/{dir_name}/mav0/imu0/data.csv', index=False)
    print(df.columns)

Home_Office_Capture_800p
Index(['#timestamp [ns]', 'w_RS_S_x [rad s^-1]', 'w_RS_S_y [rad s^-1]',
       'w_RS_S_z [rad s^-1]', 'a_RS_S_x [m s^-2]', 'a_RS_S_y [m s^-2]',
       'a_RS_S_z [m s^-2]'],
      dtype='object')
Virtana_Office_Capture_800p
Index(['#timestamp [ns]', 'w_RS_S_x [rad s^-1]', 'w_RS_S_y [rad s^-1]',
       'w_RS_S_z [rad s^-1]', 'a_RS_S_x [m s^-2]', 'a_RS_S_y [m s^-2]',
       'a_RS_S_z [m s^-2]'],
      dtype='object')
Virtana_Office_Hard_Capture_400p
Index(['#timestamp [ns]', 'w_RS_S_x [rad s^-1]', 'w_RS_S_y [rad s^-1]',
       'w_RS_S_z [rad s^-1]', 'a_RS_S_x [m s^-2]', 'a_RS_S_y [m s^-2]',
       'a_RS_S_z [m s^-2]'],
      dtype='object')
Home_Office_Capture_400p
Index(['a_RS_S_y [m s^-2]', '#timestamp [ns]', 'w_RS_S_x [rad s^-1]',
       'a_RS_S_x [m s^-2]', 'w_RS_S_z [rad s^-1]', 'w_RS_S_y [rad s^-1]',
       'w_RS_S_x [rad s^-1].1'],
      dtype='object')

In [63]:
df.head(5)

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1728579998420670976,0.010653,-0.010653,0.001065,-9.816887,0.402226,-0.266830
1,1728579998425335808,0.018109,-0.015979,-0.002131,-9.809372,0.408799,-0.255570
2,1728579998430425856,0.013848,-0.018109,-0.007457,-9.780775,0.420238,-0.267009
3,1728579998435260928,0.014914,-0.014914,-0.008522,-9.770946,0.401390,-0.233379
4,1728579998440634112,0.015979,-0.021305,-0.008522,-9.738954,0.379990,-0.211019

In [3]:
dir_name = 'Home_Office_Capture_400p'

In [ ]:
df = pd.read_csv(f'{path}/{dir_name}/mav0/imu0/data.csv')
cols = ['#timestamp [ns]', 'w_RS_S_x [rad s^-1]', 'w_RS_S_y [rad s^-1]',
   'w_RS_S_z [rad s^-1]', 'a_RS_S_x [m s^-2]', 'a_RS_S_y [m s^-2]',
   'a_RS_S_z [m s^-2]']
df = df[cols]

In [64]:
df.to_csv(f'{path}/{dir_name}/mav0/imu0/data.csv', index=False)

In [59]:
f'{path}/{dir_name}/mav0/imu0/data.csv'

'/home/shiva/Datasets/V2_01_easy/V2_01_easy/Custom_Datasets//Virtana_Office_Capture_400p/mav0/imu0/data.csv'

In [5]:
accelerometer_df = pd.read_csv(f'{path}/{dir_name}/mav0/imu0/acc_data.csv')
gyroscope_df = pd.read_csv(f'{path}/{dir_name}/mav0/imu0/gyro_data.csv')

NameError: name 'dir_name' is not defined

In [42]:
accelerometer_df.head(5)

,#timestamp [ns],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1728579998418673152,-9.806650,0.402226,-0.287304
1,1728579998422411008,-9.825804,0.402226,-0.248997
2,1728579998430934016,-9.777920,0.421380,-0.268151
3,1728579998434235136,-9.768343,0.411803,-0.248997
4,1728579998438009088,-9.777920,0.373495,-0.191536

In [43]:
gyroscope_df.head(5)

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1]
0,1728579998420670976,0.010653,-0.010653,0.001065
1,1728579998425335808,0.018109,-0.015979,-0.002131
2,1728579998430425856,0.013848,-0.018109,-0.007457
3,1728579998435260928,0.014914,-0.014914,-0.008522
4,1728579998440634112,0.015979,-0.021305,-0.008522

In [44]:
from scipy import interpolate
import numpy as np

def interpolate_data_corrected(df: pd.DataFrame, x_col: str, y_col: str, orig_timestamps: np.array) -> np.array:
    interpolated_values = []
    interpolated_values.append(df[y_col].values[0])
    for orig_timestamp in orig_timestamps[1:]:
        # print("Looking for: ", orig_timestamp)
        lower_bound_idx = df[df[x_col] <= orig_timestamp].index.max()
        upper_bound_idx = df[df[x_col] > orig_timestamp].index.min()
        # print(f"Found between indicies {lower_bound_idx} and {upper_bound_idx}.")
        bounds_df = df.iloc[lower_bound_idx: upper_bound_idx+1]
        # print(bounds_df)
        interpolation_fn = interpolate.interp1d(bounds_df[x_col].values, bounds_df[y_col].values, kind='linear')
        # print(interp_fn(orig_timestamp))
        interpolated_values.append(interpolation_fn(orig_timestamp))
    return interpolated_values

In [45]:
accelerometer_columns = ["#timestamp [ns]", "a_RS_S_x [m s^-2]", "a_RS_S_y [m s^-2]", "a_RS_S_z [m s^-2]"]

x_col = "#timestamp [ns]"
gyroscope_timestamps = gyroscope_df[x_col].values

for y_col in accelerometer_columns[1:]:
    print(f"Performing interpolation for {y_col}")
    interpolated_data = interpolate_data_corrected(accelerometer_df, x_col, y_col, gyroscope_timestamps)
    accelerometer_df[y_col] = interpolated_data
    accelerometer_df[y_col] = accelerometer_df[y_col].apply(lambda x: f"{x:.5f}")

Performing interpolation for a_RS_S_x [m s^-2]
Performing interpolation for a_RS_S_y [m s^-2]
Performing interpolation for a_RS_S_z [m s^-2]

In [46]:
accelerometer_df[x_col] = gyroscope_timestamps[0:len(interpolated_data)]

In [47]:
accelerometer_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21440 entries, 0 to 21439
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   #timestamp [ns]    21440 non-null  int64
 1   a_RS_S_x [m s^-2]  21440 non-null  object
 2   a_RS_S_y [m s^-2]  21440 non-null  object
 3   a_RS_S_z [m s^-2]  21440 non-null  object
dtypes: int64(1), object(3)
memory usage: 670.1+ KB

In [48]:
accelerometer_df.head(5)

       #timestamp [ns] a_RS_S_x [m s^-2] a_RS_S_y [m s^-2] a_RS_S_z [m s^-2]
0  1728579998420670976          -9.80665           0.40223          -0.28730
1  1728579998425335808          -9.80937           0.40880          -0.25557
2  1728579998430425856          -9.78077           0.42024          -0.26701
3  1728579998435260928          -9.77095           0.40139          -0.23338
4  1728579998440634112          -9.73895           0.37999          -0.21102

In [49]:
imu_df = accelerometer_df.merge(gyroscope_df, left_on=x_col, right_on=x_col)

# Ensuring that columns in the order Kimera-VIO expects!
imu_df = imu_df[['#timestamp [ns]','w_RS_S_x [rad s^-1]', 'w_RS_S_y [rad s^-1]', 'w_RS_S_z [rad s^-1]', 'a_RS_S_x [m s^-2]', 
                    'a_RS_S_y [m s^-2]', 'a_RS_S_z [m s^-2]']]
imu_df.to_csv(f'{path}/{dir_name}/mav0/imu0/data.csv', index=False)

In [16]:
path = '/home/shiva/Datasets/V2_01_easy/V2_01_easy'

In [17]:
imu_df = pd.read_csv(f'{path}/mav0/imu0/data.csv')

In [18]:
imu_df.head(5)

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1728579998420670976,0.010653,-0.010653,0.001065,-9.80665,0.40223,-0.28730
1,1728579998425335808,0.018109,-0.015979,-0.002131,-9.80937,0.40880,-0.25557
2,1728579998430425856,0.013848,-0.018109,-0.007457,-9.78077,0.42024,-0.26701
3,1728579998435260928,0.014914,-0.014914,-0.008522,-9.77095,0.40139,-0.23338
4,1728579998440634112,0.015979,-0.021305,-0.008522,-9.73895,0.37999,-0.21102

In [19]:
imu_df['a_RS_S_x [m s^-2]'] = imu_df['a_RS_S_x [m s^-2]'] * -1

In [20]:
imu_df.head(5)

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1728579998420670976,0.010653,-0.010653,0.001065,9.80665,0.40223,-0.28730
1,1728579998425335808,0.018109,-0.015979,-0.002131,9.80937,0.40880,-0.25557
2,1728579998430425856,0.013848,-0.018109,-0.007457,9.78077,0.42024,-0.26701
3,1728579998435260928,0.014914,-0.014914,-0.008522,9.77095,0.40139,-0.23338
4,1728579998440634112,0.015979,-0.021305,-0.008522,9.73895,0.37999,-0.21102

In [21]:
imu_df.to_csv(f'{path}/mav0/imu0/data.csv', index=False)