In [14]:
import pandas as pd

In [15]:
base_dir = '/home/shiva/Datasets/'
working_dir = 'mav0'

full_dir_path = f'{base_dir}/{working_dir}/imu0/data.csv'

In [16]:
df = pd.read_csv(full_dir_path)

In [17]:
df

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1740757289020826112,-0.004261,-0.002131,-0.004261,-9.68215,-0.85234,-0.93853
1,1740757289025516032,0.004261,0.001065,0.002131,-9.68215,-0.86758,-0.90980
2,1740757289030458880,0.003196,-0.003196,-0.001065,-9.68190,-0.86241,-0.90980
3,1740757289035880192,-0.001065,-0.003196,0.000000,-9.68724,-0.86640,-0.92935
4,1740757289040805120,-0.002131,-0.009587,-0.001065,-9.68038,-0.85582,-0.91672
...,...,...,...,...,...,...,...
14014,1740757359077177088,-0.005326,0.008522,0.000000,-9.71314,-0.89515,-0.98501
14015,1740757359082138112,-0.003196,0.008522,-0.002131,-9.70220,-0.87327,-0.96860
14016,1740757359087499008,-0.004261,-0.002131,-0.002131,-9.71510,-0.87149,-0.98836
14017,1740757359092647936,-0.005326,-0.002131,0.002131,-9.71695,-0.87149,-1.02216
14018,1740757359097435904,0.002131,-0.002131,0.005326,-9.71146,-0.87149,-1.03314

In [26]:
cols = list(df.columns)

In [27]:
cols

['#timestamp [ns]',
 'w_RS_S_x [rad s^-1]',
 'w_RS_S_y [rad s^-1]',
 'w_RS_S_z [rad s^-1]',
 'a_RS_S_x [m s^-2]',
 'a_RS_S_y [m s^-2]',
 'a_RS_S_z [m s^-2]']

In [28]:
del cols[0]

In [29]:
del cols[0]

In [30]:
del cols[0]

In [32]:
del cols[1]

In [33]:
del cols[1]

In [34]:
cols

['w_RS_S_z [rad s^-1]', 'a_RS_S_z [m s^-2]']

In [35]:
for col in cols:
    df[col] = df[col] * -1

In [36]:
df

,#timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]
0,1740757289020826112,-0.004261,-0.002131,0.004261,-9.68215,-0.85234,0.93853
1,1740757289025516032,0.004261,0.001065,-0.002131,-9.68215,-0.86758,0.90980
2,1740757289030458880,0.003196,-0.003196,0.001065,-9.68190,-0.86241,0.90980
3,1740757289035880192,-0.001065,-0.003196,-0.000000,-9.68724,-0.86640,0.92935
4,1740757289040805120,-0.002131,-0.009587,0.001065,-9.68038,-0.85582,0.91672
...,...,...,...,...,...,...,...
14014,1740757359077177088,-0.005326,0.008522,-0.000000,-9.71314,-0.89515,0.98501
14015,1740757359082138112,-0.003196,0.008522,0.002131,-9.70220,-0.87327,0.96860
14016,1740757359087499008,-0.004261,-0.002131,0.002131,-9.71510,-0.87149,0.98836
14017,1740757359092647936,-0.005326,-0.002131,-0.002131,-9.71695,-0.87149,1.02216
14018,1740757359097435904,0.002131,-0.002131,-0.005326,-9.71146,-0.87149,1.03314

In [37]:
df.to_csv(f'{base_dir}/{working_dir}/imu0/data_inverted.csv', index=False)